[package]
description = "Cap9 Ewasm Kernel Library"
name = "ewasm"
version = "0.1.0"
authors = ["Daohub Inc <info@daohub.io>"]
edition = "2018"

[dependencies]
ewasm-validator = { path = "./validator" }